### PR TITLE
add composer.json

### PR DESCRIPTION
**Pull request by pnu**
Please consider adding `composer.json` and git tag (eg. `v1.2.1`), and publishing the repo to packagist.org. This would allow direct installs with composer.

At the moment I need to have this repo fork just to install the latest version.

### CODE REVIEW

**Comment by tillkruss** [comment]
Sure, I'll do that shortly!

**Comment by pnu** [comment]
Thanks a lot! Could you add git tags like `v1.2.1` to the github repo (and sync to packagist.org)? This would allow referencing the version number. Now there is only version `dev-master` in the packagist listing. https://getcomposer.org/doc/02-libraries.md#tags

**Comment by tillkruss** [comment]
Yes, of course. I'm gonna do that in a couple of days when I get home and release 1.2.1.

**Comment by tillkruss** [comment]
`1.2.1` is live.

**Pull request merged**
